#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# lan-wsl.sh — Run from WSL
#
# Detects the Windows host LAN IP, updates docker-compose
# environment variables, and (re)starts the containers so
# the app is reachable from other machines on the local network.
#
# Usage:
#   bash scripts/lan-wsl.sh build    # build images (needs internet)
#   bash scripts/lan-wsl.sh          # start / restart (no internet needed)
#   bash scripts/lan-wsl.sh stop     # tear down
# ──────────────────────────────────────────────────────────────
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
COMPOSE_FILE="$PROJECT_DIR/docker-compose.prod.yml"
OVERRIDE_FILE="$PROJECT_DIR/docker-compose.lan.yml"

# ── Build mode (requires internet) ───────────────────────────
if [[ "${1:-}" == "build" ]]; then
  echo "[lan-wsl] Pulling Docker images (requires internet)..."
  docker compose -f "$COMPOSE_FILE" pull
  echo "[lan-wsl] Build complete. Switch to your private network and run:"
  echo "  bash scripts/lan-wsl.sh"
  exit 0
fi

# ── Tear-down mode ────────────────────────────────────────────
if [[ "${1:-}" == "stop" ]]; then
  echo "[lan-wsl] Stopping containers..."
  if [[ -f "$OVERRIDE_FILE" ]]; then
    docker compose -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" down
    rm -f "$OVERRIDE_FILE"
    echo "[lan-wsl] Removed $OVERRIDE_FILE"
  else
    docker compose -f "$COMPOSE_FILE" down
  fi
  echo "[lan-wsl] Done."
  exit 0
fi

# ── Detect Windows host LAN IP ───────────────────────────────
# The default gateway from WSL's perspective is the Windows host.
# We resolve its LAN-facing IP via PowerShell on the host.
echo "[lan-wsl] Detecting Windows host LAN IP..."

# Allow manual override first
if [[ -n "${LAN_IP:-}" ]]; then
  HOST_IP="$LAN_IP"
else
  HOST_IP=$(powershell.exe -NoProfile -Command "
    \$ip = (Get-NetIPConfiguration |
      Where-Object { \$_.IPv4DefaultGateway -ne \$null } |
      Select-Object -First 1).IPv4Address.IPAddress
    Write-Output \$ip
  " 2>/dev/null | tr -d '\r\n')
fi

if [[ -z "$HOST_IP" ]]; then
  echo "[lan-wsl] ERROR: Could not detect Windows host LAN IP."
  echo "[lan-wsl] You can set it manually:  LAN_IP=192.168.x.x bash scripts/lan-wsl.sh"
  exit 1
fi

echo "[lan-wsl] Windows host LAN IP: $HOST_IP"

# ── Generate docker-compose override ─────────────────────────
cat > "$OVERRIDE_FILE" <<EOF
# Auto-generated by lan-wsl.sh — do not commit
services:
  frontend:
    environment:
      - VITE_API_URL=http://${HOST_IP}:3333
EOF

echo "[lan-wsl] Generated $OVERRIDE_FILE"
echo ""
cat "$OVERRIDE_FILE"
echo ""

# ── Start / restart containers ────────────────────────────────
echo "[lan-wsl] Starting containers..."
docker compose -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" up -d

echo ""
echo "============================================="
echo "  App is running on LAN"
echo "  Frontend: http://${HOST_IP}"
echo "  Backend:  http://${HOST_IP}:3333"
echo "============================================="
echo ""
echo "Now run the Windows script (PowerShell as Admin):"
echo "  .\\scripts\\lan-win.ps1"
echo ""
